var generatorsDetails = [
	{
		id: "Voter",
		name: "מצביע",
		votesPerSec: 0.2,
		description: "יצביע בשבילך כל 5 שניות לא משנה מה תעשה. כמו אנשים אחרים שאתה מכיר.",
		price: 10,
		picture: "loneVoter.png",
	},
	{
		id: "Cookie",
		name: "עוגיות",
		votesPerSec: 1,
		description: "כולם אוהבים עוגיות. במיוחד הבוחרים.",
		price: 130,
		picture: "cookies.png",
	},
	{
		id: "Campaign",
		name: "קמפיין",
		votesPerSec: 7,
		description: "מאחורי כל אדם גדול עומד קמפיין גדול.",
		price: 810,
		picture: "campaign.png",
	},
	{
		id: "Rabi",
		name: "רב",
		votesPerSec: 30,
		description: "כל ממשלה צריכה אחד.<br>ועוד אחד לספרדים.",
		price: 8100,
		picture: "rabi.png",
<<<<<<< HEAD
	},
	{
		id: "Gays",
		name: "תא גאה",
		votesPerSec: 100,
		description: "פינק וושינג? מה זה?",
		price: 49500,
		picture: "gays.png",
	},
	{
		id: "Survey",
		name: "סקר",
		votesPerSec: 1250,
		description: "מינה צמח קוראת בקלפי(ם).",
		price: 750000,
		picture: "survey.png",
	},
		{
		id: "Celebrity",
		name: "סלב",
		votesPerSec: 5300,
		description: "אם היא יודעת לשיר טוב, היא יודעת גם מה טוב בשבילי.",
		price: 15500000,
		picture: "celeb.png",
	},
		{
		id: "Army",
		name: "מבצע צבאי",
		votesPerSec: 40000,
		description: "תראו שם! הסחת דעת!<BR> (אמור לעלות 7 מצביעים, לא שקלים)",
		price: 7,
		picture: "army.png",
	},
		{
		id: "Baby",
		name: "הפרייה מלאכותית",
		votesPerSec: 100000,
		description: "של תינוקות מושלמים. שיצביעו לך.",
		price: 57000500,
		picture: "baby.png",
	},
		{
		id: "Satan",
		name: "עסקה עם השטן",
		votesPerSec: 66666666,
		description: "היישות השנייה בעוצמתה...",
		price: 66000000,
		picture: "satan.png",
	},
		{
		id: "Owl",
		name: "ינשוף",
		votesPerSec: 1234567890,
		description: "אל תשאל.",
		price: 345000000000,
		picture: "owl.png",
=======
>>>>>>> parent of eb39365... Added new generators, tweaked CSS and applied numNamers
	}
]
